### ISSUE TITLE
Two rules are causing errors

### ISSUE THREAD

**Issue by miketrexler** [hzdg/linter-configs#27]
When running `eslint` command, the following rules are causing eslint to crash. The only way I am able to run eslint is by disabling these rules.:

**"indent": [2, 2, {"indentSwitchCase": true}],**

```
/node_modules/eslint/lib/config-validator.js:93
        throw new Error(message.join(""));
              ^
Error: /Users/mtt/_Projects/redux-playground/redux-advanced-example/.eslintrc:
    Configuration for rule "indent" is invalid:
    Value "data["2"].indentSwitchCase" has additional properties.

    at validateRuleOptions (/Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/config-validator.js:93:15)
    at /Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/config-validator.js:106:13
    at Array.forEach (native)
    at Object.validate (/Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/config-validator.js:105:35)
    at loadConfig (/Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/config.js:137:19)
    at getLocalConfig (/Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/config.js:273:23)
    at Config.getConfig (/Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/config.js:405:22)
    at processText (/Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/cli-engine.js:181:27)
    at processFile (/Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/cli-engine.js:224:12)
    at /Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/cli-engine.js:391:26
```

**"no-duplicate-case": 2,**

```
/node_modules/eslint/lib/rules/no-duplicate-case.js:24
            if (!~["loc", "start", "end", "range"].indexOf(prop)) {
                                                   ^
RangeError: Maximum call stack size exceeded
    at Array.indexOf (native)
    at stripsPosition (/Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/rules/no-duplicate-case.js:24:52)
    at stripsPosition (/Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/rules/no-duplicate-case.js:27:36)
    at stripsPosition (/Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/rules/no-duplicate-case.js:27:36)
    at stripsPosition (/Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/rules/no-duplicate-case.js:27:36)
    at stripsPosition (/Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/rules/no-duplicate-case.js:27:36)
    at stripsPosition (/Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/rules/no-duplicate-case.js:27:36)
    at stripsPosition (/Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/rules/no-duplicate-case.js:27:36)
    at stripsPosition (/Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/rules/no-duplicate-case.js:27:36)
    at stripsPosition (/Users/mtt/_Projects/redux-playground/redux-advanced-example/node_modules/eslint/lib/rules/no-duplicate-case.js:27:36)
```

**Comment by aamorozov** [comment]
Closing since the pr was merged a while ago
